---
title: "csf_troubleshoting"
output: html_document
date: "2025-03-31"
---

```{r}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(dplyr)
library(gamlss)
devtools::install_github("BGDlab/gamlssTools", force=TRUE)
library(gamlssTools)

source("./code/gamlss_fit_funs.R")
```

```{r}
cv_B <- fread("./data/cv_sample_B.csv", stringsAsFactors = TRUE, na.strings = "")
cv_A <- fread("./data/cv_sample_A.csv", stringsAsFactors = TRUE, na.strings = "")
```

```{r}
df_csf <- cv_B %>%
  dplyr::select(all_of(c("CSF", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days"))) %>%
  na.omit()

df_wmv<- cv_B %>%
  dplyr::select(all_of(c("WMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days"))) %>%
  na.omit()

df_gmv<- cv_A %>%
  dplyr::select(all_of(c("GMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days"))) %>%
  na.omit()
```

test coverage along log age

```{r}
ggplot(df_csf) +
  geom_point(aes(x=logAge_days, y= CSF, color=as.factor(sexMale)), alpha=.2)

ggplot(df_wm) +
  geom_point(aes(x=logAge_days, y= WMV, color=as.factor(sexMale)), alpha=.2)

range(df_csf$logAge_days)
range(df_wm$logAge_days)

range(df_csf$sexMale_x_logAge)
range(df_wm$sexMale_x_logAge)

range(df_csf$CSF)
range(df_wm$WMV)
```

```{r}
df_csf %>%
  arrange(logAge_days) %>%
  mutate(age_group = cut(logAge_days, breaks = 8, labels = paste0("G", 1:8))) %>%
  ggplot(aes(x=CSF, fill=as.factor(sexMale))) +
  geom_histogram(position="identity", alpha=.6) +
  facet_wrap(~age_group, scales = "free")
```

```{r}
trunc_coverage(df_wm, "logAge_days")

test_csf <- trunc_coverage(df_csf, "logAge_days", n_min=50)
range(test_csf$CSF)
range(test_csf$logAge_days)
```
```{r}
test_mod1 <- gamlss(formula = CSF ~ pb(sexMale_x_logAge, control = pb.control(order = 3)) + 
    pb(logAge_days, control = pb.control(order = 3)) + sexMale + 
    random(study_site) + fs_version_GM, 
    sigma.formula = ~pb(sexMale_x_logAge,  
    control = pb.control(order = 3)) + pb(logAge_days, control = pb.control(order = 3)) + 
    sexMale + random(study_site) + fs_version_GM, 
    nu.formula = ~ pb(logAge_days, control = pb.control(order = 3)) + sexMale, 
    family = BCCG, data = df_csf,
    control = gamlss.control(n.cyc = 200, nu.step = 0.25), trace = FALSE)

make_centile_fan(gamlssModel=test_mod1, df=df_csf, x_var="logAge_days", color_var="sexMale",
                             get_peaks=FALSE, desiredCentiles=c(0.05, 0.25, 0.5, 0.75, 0.95),                             
                             special_term = "sexMale_x_logAge = sexMale * logAge_days")
```

```{r}
test_mod2 <- gamlss(formula = CSF ~
    pb(logAge_days, control = pb.control(order = 3)) + sexMale + 
    random(study_site) + fs_version_GM, sigma.formula = ~ pb(logAge_days, control = pb.control(order = 3)) + 
    sexMale + random(study_site) + fs_version_GM, nu.formula = ~logAge_days + 
    fs_version_GM, family = GG, data = df_csf, 
    control = gamlss.control(n.cyc = 200, nu.step = 0.25), trace = FALSE)

make_centile_fan(gamlssModel=test_mod2, df=df_csf, x_var="logAge_days", color_var="sexMale",
                             get_peaks=FALSE, desiredCentiles=c(0.05, 0.25, 0.5, 0.75, 0.95))
```

```{r}
test_mod3 <- gamlss(formula = CSF ~
    pb(logAge_days, control = pb.control(order = 3)) + sexMale + 
    random(study_site) + fs_version_GM, sigma.formula = ~ pb(logAge_days, control = pb.control(order = 3)) + 
    sexMale + random(study_site) + fs_version_GM, nu.formula = ~logAge_days + 
    fs_version_GM, tau.formula = ~ logAge_days, family = BCT, data = df_csf, 
    control = gamlss.control(n.cyc = 200, nu.step = 0.25), trace = FALSE)

make_centile_fan(gamlssModel=test_mod3, df=df_csf, x_var="logAge_days", color_var="sexMale",
                             get_peaks=FALSE, desiredCentiles=c(0.05, 0.25, 0.5, 0.75, 0.95))
```

#Look into issues with eTIV

```{r}
df_sgmv<- cv_B %>%
  dplyr::select(all_of(c("sGMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days", "eTIV"))) %>%
  na.omit()

ggplot(df_sgmv) +
  geom_point(aes(x=eTIV, y=sGMV))
```

```{r}
trunc_df <- trunc_coverage(df_sgmv, "eTIV")
ggplot(trunc_df) +
  geom_point(aes(x=eTIV, y=sGMV))

ggplot(trunc_df) +
  geom_point(aes(x=age_days, y=eTIV))
ggplot(df_sgmv) +
  geom_point(aes(x=age_days, y=eTIV))
min(trunc_df$age_days)
min(df_sgmv$age_days)
```
age and etiv together
```{r}
trunc_df2 <- trunc_coverage(df_sgmv, c("eTIV", "logAge_days"))
#check age again
trunc_coverage(trunc_df2, "logAge_days")

trunc_df3 <- cv_B %>%
  dplyr::select(all_of(c("sGMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days", "eTIV"))) %>%
  na.omit() %>%
  trunc_coverage(c("eTIV", "logAge_days"))
```


```{r}
ggplot(df_gmv) +
  geom_point(aes(x=logAge_days, y=GMV, color=as.factor(sexMale)), alpha=.2)

#model without pb in nu
gmv_mod2 <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/GMV_unweighted_lambdaNULL_mu_age_mod.rds")

make_centile_fan(gmv_mod2, df_gmv, "logAge_days", "sexMale", 
                 remove_point_effect ="study_site", remove_cent_effect="study_site") #looks very bad!
```

looks really bad, checking out other models

```{r}
#model without pb in nu
gmv_mod3 <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/GMV_unweighted_lambdaNULL_both_age_mod.rds")

make_centile_fan(gmv_mod3, df_gmv, "logAge_days", "sexMale") #looks very bad!

#model without pb in nu
gmv_mod4 <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/GMV_unweighted_lambdaNULL_mu_sex_pbAge_mod.rds")

make_centile_fan(gmv_mod4, df_gmv, "logAge_days", "sexMale") #looks very bad!

#model without pb in nu
gmv_mod5 <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/GMV_unweighted_lambdaNULL_mu_sexAge_mod.rds")

make_centile_fan(gmv_mod5, df_gmv, "logAge_days", "sexMale") #looks very bad!
```

try refitting best mod with BCCG()

```{r}
gmv_best <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/GMV_unweighted_lambdaNULL_mu_pbage_BestMod.rds")

gmv_refit <- gamlss(formula = GMV ~ pb(sexMale_x_logAge, control = pb.control(order = 3)) + 
    pb(logAge_days, control = pb.control(order = 3)) + sexMale + random(study_site) + fs_version_GM, 
    sigma.formula = ~pb(sexMale_x_logAge, control = pb.control(order = 3)) + pb(logAge_days, control = pb.control(order = 3)) + sexMale + random(study_site), 
    nu.formula = ~pb(logAge_days, control = pb.control(order = 3)), 
    family = BCCG, data = df_gmv, 
    method = RS(), control = gamlss.control(n.cyc = 200, 
        nu.step = 0.25), trace = FALSE)
```