---
title: "plot toubleshooting"
output: html_document
date: "2025-04-01"
---


```{r}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(dplyr)
library(gamlss)
library(gamlssTools)

source("./code/gamlss_fit_funs.R")
```

```{r}
cv_B <- fread("./data/cv_sample_B.csv", stringsAsFactors = TRUE, na.strings = "")
```

```{r}
wmv_total_mod <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_B_train/cv_sample_B_global_vols_mods/model_objs/WMV_unweighted_lambdaNULL_fsall_age_totalmu_BestMod.rds")

wmv_mod <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_B_train/cv_sample_B_global_vols_mods/model_objs/WMV_unweighted_lambdaNULL_all_int_BestMod.rds")

df_wm <- cv_B %>%
  dplyr::select(all_of(c("WMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days"))) %>%
  na.omit()

df_wm_tot <- cv_B %>%
  dplyr::select(all_of(c("WMV", "fs_version_GM", "eTIV", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days"))) %>%
  na.omit()
```

```{r}
make_centile_fan(gamlssModel=wmv_total_mod, df=df_wm_tot, x_var="eTIV", color_var="sexMale",
                             get_peaks=FALSE, desiredCentiles=c(0.05, 0.5,0.95),
                 remove_point_effect = c("fs_version_GM")) +
  ggtitle("residualized")

make_centile_fan(gamlssModel=wmv_total_mod, df=df_wm_tot, x_var="eTIV", color_var="sexMale",
                             get_peaks=FALSE, desiredCentiles=c(0.05, 0.5,0.95)) +
  ggtitle("base model")
```