---
title: "Prelim_HBCD_eda"
output: html_document
date: "2025-03-14"
---

```{r}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

Incorporating preliminary HBCD data (pre-release) into LBCC v3  for growth charts

```{r, warning=FALSE}}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, tidyverse, stats, skimr, naniar, rlang, parallel, ggrepel, ggpubr)
```

#tabular imaging df

```{r}
imaging_df <- fread("/mnt/isilon/bgdlab_processing/Data/HBCD/HBCD_tabular_downloads/imaging/bibset_segmentation/data.csv", na.strings = c("", NA))
#names(imaging_df)
names(imaging_df)[grep("age", names(imaging_df))]
skim(imaging_df$img_mriqc_T2w_candidate_age)

imaging_df %>%
  select(all_of(names(imaging_df)[grep("age", names(imaging_df))])) %>%
  skim()

imaging_df_filt <- imaging_df %>%
  rename(age = img_mriqc_T2w_candidate_age) %>%
  dplyr::select(!any_of(starts_with("img_mriqc"))) #dropping qc for now, since this is just the beta release

colnames(imaging_df_filt) <- gsub("img_bibsnet_space-T2w_desc-aseg_volumes_", "", colnames(imaging_df_filt))
```

#M-CRIB Imaging Outputs
need to compile across subject-specific dirs

```{r}
mcrib_df <- fread("/mnt/isilon/bgdlab_processing/Data/HBCD/HBCD_justMCRIB_21March2025/HBCD_beta_MCRIB_freesurfer_aparcaseg_volumes.csv")
skim(mcrib_df)

mcrib_df <- mcrib_df %>%
  rename("id" = "subject") %>%
  filter_all(any_vars(!is.na(.)))
```


compare dfs
```{r}
n_unique(mcrib_df$id)
n_unique(imaging_df_filt$id)

intersect(names(imaging_df_filt), names(mcrib_df))

skim(mcrib_df)
skim(imaging_df_filt)
```

test merge
```{r}
test_df <- full_join(imaging_df_filt, mcrib_df)
names(test_df)

ggplot(test_df) +
  geom_point(aes(x=age, y=CSF), alpha=.4)
ggplot(test_df) +
  geom_point(aes(x=age, y=`Right-Amygdala`), alpha=.4)
ggplot(test_df) +
  geom_point(aes(x=age, y=`Right-Lateral-Ventricle`), alpha=.4)
```

looks pretty reasonable

#Demographics

```{r}
demo_df <- fread("/mnt/isilon/bgdlab_processing/Data/HBCD/HBCD_tabular_downloads/nonimaging/demographics/DATA_CSV14096344619509598011.csv", na.strings = c("", NA))
#names(demo_df)
unique(demo_df$par_visit_data_par_visit_data_cohort)
unique(demo_df$par_visit_data_par_visit_data_project)

demo_sub <- demo_df %>%
  dplyr::select(id, visit_label, cohort, site, sed_basic_demographics_sed_basic_demographics_sex) %>%
  rename(sex = sed_basic_demographics_sed_basic_demographics_sex) %>%
  mutate(sex = ifelse(sex=="Unknown", NA, sex)) %>%
  na.omit()
```

Merge!
```{r}
n_unique(demo_sub$id)
n_unique(test_df$id)

hbcd <- inner_join(demo_sub, test_df) %>%
  select_if(~!all(is.na(.))) %>% #drop col if all is empty
  drop_na(age, sex)

skim(hbcd)

n_unique(hbcd$id)

length(intersect(demo_sub$id, mcrib_df$id))
fwrite(hbcd, "/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/data/beta_hbcd.csv")
```