---
title: "Review Test Models"
output: html_document
date: "2024-10-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

```{r, warning=FALSE}}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, tidyverse, stats, skimr, rlang, ggrepel, gamlss, ggseg, ggsegExtra, RESI, paletteer, patchwork)

#devtools::install_github("BGDlab/gamlssTools", force=TRUE)
library(gamlssTools)
library(ggsegTissue)

sa_list <- readRDS("./pheno_lists/cortical_surf.rds")
ct_list <- readRDS("./pheno_lists/cortical_thickness.rds")
vol_list <- readRDS("./pheno_lists/cortical_vols.rds")
global_list <- readRDS("./pheno_lists/global_vols.rds")
sub_list <- readRDS("./pheno_lists/subcortical_vols.rds")
pheno_list <- c(sa_list, ct_list, vol_list, global_list, sub_list)
test_path <- "/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_?_test/*/model_sums/"

# install.packages("remotes")
remotes::install_github("BGDlab/ggsegTissue")
# install.packages("remotes")
remotes::install_github("ggseg/ggsegExtra")
```

#Read & Prep CSVs
```{r}
# Use Sys.glob to expand wildcard paths
paths <- Sys.glob(file.path(test_path, "*LRtest.csv"))

# Read all matching CSVs
output_fread <- lapply(paths, fread)
length(output_fread)
names(output_fread) <- paths
#stringr::str_extract(paths, "(?<=cv_sample_)[A-Za-z]+(?=_test)")


LR.df <- bind_rows(output_fread, .id="file") %>%
  mutate(cv_sample = stringr::str_extract(file, "(?<=cv_sample_)[A-Za-z]+(?=_test)"),
         total = stringr::str_extract(file, "(?<=total)(TRUE|FALSE)")) %>%
  select(!file)
```

Get RESI effect size

```{r}
LR.df2 <- LR.df %>%
  mutate(resi = fsq2S(fsq),
         pheno_cat = factor(case_when(
    pheno %in% global_list ~ "Global Vol",
    pheno %in% vol_list ~ "Regional Vol",
    pheno %in% sub_list ~ "Subcortical Vol",
    pheno %in% sa_list ~ "Regional SA",
    pheno %in% ct_list ~ "Regional CT",
    TRUE ~ NA_character_)),
)

table(LR.df2$effect, LR.df2$total)
```

Prep atlases for plotting

```{r}
#clean up atlases to remove non-modeled phenos
#write out new dk atlas w/o medial wall
dk_clean <- dk
dk_clean$data <- dk_clean$data %>%
  dplyr::filter(!is.na(region) & region !="corpus callosum")

aseg_clean <- aseg
aseg_clean$data <- aseg_clean$data %>%
  dplyr::filter(!is.na(label))

aseg_all_clean <- aseg_all
aseg_all_clean$data <- aseg_all_clean$data %>%
  dplyr::filter(label != "Brain-Stem")
```

```{r}
# sub_list
# unique(aseg$data$label)

LR.df_plot <- LR.df2 %>%
  mutate(label = case_when(
    pheno %in% sub_list ~ gsub("^SUBC\\.", "", pheno),
    TRUE ~ gsub("\\.(SA|GM|CT)\\.", "_", pheno))) %>%
  mutate(label = gsub("\\.", "-", label)) %>%
  mutate(label = ifelse(label == "3rd-Ventricle", "x3rd-ventricle", label)) %>%
  mutate(label = ifelse(label == "4th-Ventricle", "x4th-ventricle", label)) %>%
  mutate(tissue_class = case_when(
    pheno == "sGMV" ~ "sGM",
    pheno == "GMV" ~ "cGM",
    pheno == "WMV" ~ "WM",
    pheno == "CSF" ~ "CSF",
    pheno == "CBV" ~ "Cerebellum",
    pheno == "SUBC.Brain.Stem" ~ "Brainstem",
    TRUE ~ NA_character_
  ))
LR.df_plot$cv_sample <- factor(LR.df_plot$cv_sample, levels = c("A", "B"))

#check cortical
setdiff(unique(dk$data$label), unique(LR.df_plot$label)) #corpus callosum is subdivided - remove from dk plots

#check subcortical
setdiff(unique(aseg$data$label), unique(LR.df_plot$label)) # all included

#check global
setdiff(unique(aseg_all$data$tissue_class), unique(LR.df_plot$tissue_class)) # all included

#see what's not included anywhere
setdiff(unique(LR.df_plot$label), c(unique(dk$data$label), unique(aseg$data$label)))
```

"Left-Accumbens-area", "Right-Accumbens-area", "Left-Cerebellum-Cortex" & "Left-Cerebellum-White-Matter" aren't in field of view for aseg atlas

#Non-Corrected Model

```{r}
LR.df_uncor <- LR.df_plot %>%
  dplyr::filter(total==FALSE) %>%
  mutate(p.val_fdr = p.adjust(p_val, method="fdr", n = nrow(LR.df))) %>%
  mutate(sig_fdr = ifelse(p.val_fdr <=0.05, TRUE, FALSE)) %>%
  mutate(sig_fsq = ifelse(sig_fdr==TRUE, fsq, NA),
         sig_resi = ifelse(sig_fdr==TRUE, resi, NA))

table(LR.df_uncor$sig_fdr)

ggplot(LR.df_uncor) +
  geom_histogram(aes(x=sig_resi, fill=pheno_cat), position='identity', alpha=0.6) +
  facet_wrap(~cv_sample)

range(LR.df_uncor$sig_fsq, na.rm=T)
range(LR.df_uncor$sig_resi, na.rm=T)
```


```{r}
cort_plt_uncor <- LR.df_uncor %>%
  filter(pheno_cat == "Regional Vol" | pheno_cat == "Regional SA" | pheno_cat == "Regional CT") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = dk_clean, 
             position = position_brain(hemi ~ side),
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample) 

sub_plt_uncor <- LR.df_uncor %>%
  filter(pheno_cat == "Subcortical Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)

LR.df_plot_glob_uncor <- inner_join(LR.df_uncor, aseg_all_clean$data, by="tissue_class")
glob_plt_uncor <- LR.df_plot_glob_uncor %>%
  filter(pheno_cat == "Global Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_all_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)
```

```{r}
full_plt_uncor <- glob_plt_uncor /plot_spacer()/ cort_plt_uncor / plot_spacer()/ sub_plt_uncor +
  plot_layout(guides = 'collect', heights = unit(c(3, -1.2, 6, -1.2, 3), c('in', 'in', 'in')))

ggsave("figs/resi_uncorrected.png", full_plt_uncor, width=7, height=10)
```

#TBV-Corrected Models

##Age*Sex Effect

```{r}
LR.df_tot <- LR.df_plot %>%
  dplyr::filter(total==TRUE & effect=="sex_age") %>%
  mutate(p.val_fdr = p.adjust(p_val, method="fdr", n = nrow(LR.df))) %>%
  mutate(sig_fdr = ifelse(p.val_fdr <=0.05, TRUE, FALSE)) %>%
  mutate(sig_fsq = ifelse(sig_fdr==TRUE, fsq, NA),
         sig_resi = ifelse(sig_fdr==TRUE, resi, NA))

table(LR.df_tot$sig_fdr)

ggplot(LR.df_tot) +
  geom_histogram(aes(x=sig_resi, fill=pheno_cat), position='identity', alpha=0.6) +
  facet_wrap(~cv_sample)

range(LR.df_tot$sig_fsq, na.rm=T)
range(LR.df_tot$sig_resi, na.rm=T)
```

```{r}
cort_plt_tot <- LR.df_tot %>%
  filter(pheno_cat == "Regional Vol" | pheno_cat == "Regional SA" | pheno_cat == "Regional CT") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = dk_clean, 
             position = position_brain(hemi ~ side),
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample) 

sub_plt_tot <- LR.df_tot %>%
  filter(pheno_cat == "Subcortical Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)

LR.df_plot_glob_tot <- inner_join(LR.df_tot, aseg_all_clean$data, by="tissue_class")
glob_plt_tot <- LR.df_plot_glob_tot %>%
  filter(pheno_cat == "Global Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_all_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Greens 3", name = "RESI", limits = c(0, 0.18), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)
```

```{r}
full_plt_tot <- glob_plt_tot /plot_spacer()/ cort_plt_tot / plot_spacer()/ sub_plt_tot +
  plot_layout(guides = 'collect', heights = unit(c(3, -1.2, 6, -1.2, 3), c('in', 'in', 'in')))
full_plt_tot
ggsave("figs/resi_tbv.png", full_plt_tot, width=7, height=10)
```

##Sex Effect

```{r}
LR.df_tot_sex <- LR.df_plot %>%
  dplyr::filter(total==TRUE & effect=="sex_all") %>%
  mutate(p.val_fdr = p.adjust(p_val, method="fdr", n = nrow(LR.df))) %>%
  mutate(sig_fdr = ifelse(p.val_fdr <=0.05, TRUE, FALSE)) %>%
  mutate(sig_fsq = ifelse(sig_fdr==TRUE, fsq, NA),
         sig_resi = ifelse(sig_fdr==TRUE, resi, NA))

table(LR.df_tot_sex$sig_fdr)

ggplot(LR.df_tot_sex) +
  geom_histogram(aes(x=sig_resi, fill=pheno_cat), position='identity', alpha=0.6) +
  facet_wrap(~cv_sample)

range(LR.df_tot_sex$sig_fsq, na.rm=T)
range(LR.df_tot_sex$sig_resi, na.rm=T)
```

```{r}
cort_plt_tot_sex <- LR.df_tot_sex %>%
  filter(pheno_cat == "Regional Vol" | pheno_cat == "Regional SA" | pheno_cat == "Regional CT") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = dk_clean, 
             position = position_brain(hemi ~ side),
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Purple-Blue", name = "RESI", limits = c(0, 0.3), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample) 

sub_plt_tot_sex <- LR.df_tot_sex %>%
  filter(pheno_cat == "Subcortical Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), strip.text.x = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Purple-Blue", name = "RESI", limits = c(0, 0.3), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)

LR.df_plot_glob_tot_sex <- inner_join(LR.df_tot_sex, aseg_all_clean$data, by="tissue_class")
glob_plt_tot_sex <- LR.df_plot_glob_tot_sex %>%
  filter(pheno_cat == "Global Vol") %>%
  ggplot() +
  theme_linedraw(base_size=12) +
  ggseg::geom_brain(atlas = aseg_all_clean, 
            aes(fill=sig_resi)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.margin = margin(0, 0, 0, 0)) +
  paletteer::scale_fill_paletteer_c("grDevices::Purple-Blue", name = "RESI", limits = c(0, 0.3), direction = -1) +
  facet_grid(pheno_cat ~ cv_sample)
```

```{r}
full_plt_tot_sex <- glob_plt_tot_sex /plot_spacer()/ cort_plt_tot_sex / plot_spacer()/ sub_plt_tot_sex +
  plot_layout(guides = 'collect', heights = unit(c(3, -1.2, 6, -1.2, 3), c('in', 'in', 'in')))
full_plt_tot_sex
ggsave("figs/resi_tbv_allsex.png", full_plt_tot_sex, width=7, height=10)
```
