---
title: "CV Model Testing"
output: html_document
date: "2025-01-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

```{r, warning=FALSE}}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, tidyverse, stats, skimr, splitstackshape, gamlss, gamlssTools, gridExtra, grid, png)

subcortical_vols <- readRDS("pheno_lists/subcortical_vols.rds")
global_vols <- readRDS("pheno_lists/global_vols.rds")
```

Testing CV models

##Split Sample A

```{r}
glob_path <- Sys.glob("cv_sample_*_train/*global_vols_mods/")
```

###Global

list best model's files for review - code with help from GPT
```{r}
pdf("global_train_mods.pdf", width = 8.5, height = 11)  # Open PDF device

best_mods <- list.files(path = paste0(glob_path, "model_objs"),
                        pattern = "*BestMod.rds", 
                        recursive = T,
                        full.names = TRUE)

for (fname in best_mods) {
  # Get plot fils
  cent_png_file <- sub("model_objs", "centile_plots", fname) %>% sub("_BestMod.rds", ".png", .)
  wp_png_file <- sub("model_objs", "worm_plots", fname) %>% sub("_BestMod.rds", ".png", .)
  cent_csv_file <- sub("model_objs", "cent_csvs", fname) %>% sub("_BestMod.rds", "_results.csv", .)
  
  if((length(cent_png_file) & length(wp_png_file) & length(cent_csv_file)) != 1){
    warning(paste("ERROR in", fname, ": found", 
               length(cent_png_file), "fan plots,", 
               length(wp_png_file), "worm plots, and", 
               length(cent_csv_file), "centile csvs"))
    next
  }
           
  img_list <- list()
  
  #plot pngs
  img_list[[1]] <- rasterGrob(as.raster(png::readPNG(cent_png_file)), interpolate = TRUE)
  img_list[[2]] <- rasterGrob(as.raster(png::readPNG(wp_png_file)), interpolate = TRUE)
  
  # Read and print CSV file
  # csv_data <- read.csv(cent_csv_file)
  # csv_table <- tableGrob(csv_data)
  
  #add section title
  pheno <- sub("_.*", "", basename(fname))
  samp <- regmatches(fname, gregexpr("(?<=cv_sample_)\\w", fname, perl = TRUE))[[1]] %>% unique()
  title <- textGrob(paste("Phenotype:", pheno, "Sample:", samp), gp = gpar(fontsize = 14, fontface = "bold"))
  grid.arrange(
    title, 
    img_list[[1]], 
    img_list[[2]],
    # csv_table,
    heights = c(.5, 3, 3, 2)  # Adjust heights for better layout
  )
}

# Close PDF
dev.off()
```

look at all lambda=40000s just to see
```{r}
pdf("subcortical_lambda40000.pdf", width = 8.5, height = 11)  # Open PDF device

l400_list <- paste(subcortical_vols, "lambda40000", sep="_")

for (fname in l400_list) {
  # Get file names
  cent_png_file <- list.files(paste0(subcort_path, "centile_plots"), pattern = fname, full.names = TRUE)
  wp_png_file <- list.files(paste0(subcort_path, "worm_plots"), pattern = fname, full.names = TRUE)
  cent_csv_file <- list.files(paste0(subcort_path, "cent_csvs"), pattern = fname, full.names = TRUE)
  
  if((length(cent_png_file) & length(wp_png_file) & length(cent_csv_file)) != 1){
    warning(paste("ERROR in", fname, ": found", 
               length(cent_png_file), "fan plots,", 
               length(wp_png_file), "worm plots, and", 
               length(cent_csv_file), "centile csvs"))
    next
  }
           
  img_list <- list()
  
  #plot pngs
  img_list[[1]] <- rasterGrob(as.raster(png::readPNG(cent_png_file)), interpolate = TRUE)
  img_list[[2]] <- rasterGrob(as.raster(png::readPNG(wp_png_file)), interpolate = TRUE)
  
  # Read and print CSV file
  csv_data <- read.csv(cent_csv_file)
  csv_table <- tableGrob(csv_data)
  
  #add section title
  title <- textGrob(paste("Phenotype:", fname), gp = gpar(fontsize = 16, fontface = "bold"))
  grid.arrange(
    title, 
    img_list[[1]], 
    img_list[[2]],
    csv_table,
    heights = c(1, 4, 5, 1)  # Adjust heights for better layout
  )
}

# Close PDF
dev.off()
```
