---
title: "Spline Testing"
output: html_document
date: "2024-12-18"
---

Playing around with different spline configurations to see how they effect worm plots. Sticking to sex-stratified models in unharmonized global phenos (using study_site as fixed effect)

```{r warning=FALSE}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, tidyverse, stats, skimr, gamlss, gamlssTools)

source("code/gamlss_fit_funs.R")
```

load data
```{r}
df_B <- fread("data/cv_sample_B.csv", stringsAsFactors=TRUE)

df_WMV <- df_B %>%
  dplyr::select(all_of(c("WMV", "fs_version_GM", "logAge_days", "sexMale", "study_site", "sexMale_x_logAge", "age_days", "sexMale_x_age", "age_days"))) %>%
  na.omit() %>%
  trunc_coverage("logAge_days")

ggplot(df_WMV) +
  geom_histogram(aes(x=logAge_days))

ggplot(df_WMV) +
  geom_histogram(aes(x=age_days/365.25))
```

```{r}
test <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_A_train/global_vols_mods/model_objs/WMV_unweighted_lambdaNULL_none_int_mod.rds")

test1 <- gamlss(formula = WMV ~ pb(sexMale_x_age, control = pb.control(order = 3)) + 
    pb(age_days, control = pb.control(order = 3)) + sexMale + random(study_site), 
    sigma.formula = ~pb(sexMale_x_age, control = pb.control(order = 3)) + pb(age_days, control = pb.control(order = 3)) + sexMale + random(study_site), 
    nu.formula = ~1, 
    family = BCCG, 
    data = df_WMV, control = gamlss.control(n.cyc = 200, nu.step = 0.25), trace = FALSE)
```