---
title: "check_convergence"
output: html_document
---

```{r, warning=FALSE}}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(dplyr, stringr)
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

```{r}
# Define the top-level directory (change this as needed)
base_dir <- "/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts"

# Find all files named 'convergence_summary.csv' recursively
csv_files <- list.files(base_dir, pattern = "*_convergence_summary\\.csv$", 
                        recursive = TRUE, full.names = TRUE)

# Check how many files were found
cat("Found", length(csv_files), "files\n")

```


```{r}
# Read and merge them all
merged_df <- csv_files[-length(csv_files)] %>%
  lapply(read.csv, stringsAsFactors = FALSE) %>%
  lapply(na.omit) %>%
  bind_rows(.id = "source_file")

# Optional: Add directory info for tracking
merged_df <- merged_df %>%
  mutate(
    source_dir = dirname(csv_files[as.integer(source_file)]),
    best_mod = stringr::str_detect(file, "BestMod"),
    weighted = stringr::str_detect(file, "weight"),
    total = stringr::str_extract(file, "(?<=total)(TRUE|FALSE)"),
    correct_pheno = ifelse(pheno==y, TRUE, FALSE)
  ) %>%
  select(where(~!all(is.na(.))))
```

Check correct pheno

```{r}
skimr::skim(merged_df)
table(merged_df$correct_pheno)
stopifnot(unique(merged_df$correct_pheno)==TRUE)
```

```{r}
merged_df %>%
  filter(converged==FALSE & best_mod == TRUE)

dnc <- merged_df %>%
  filter(converged==FALSE)

to_delete <- dnc$file
unique(dnc$weighted)

#what phenos are affected?
dnc <- dnc %>% 
  mutate(source_dir = dirname(file)) %>%
  mutate(BestMod_rename = paste0(source_dir,"/", pheno, "*BestMod.rds"),
         rm_train_cent_csvs = paste0(gsub("model_objs", "cent_csvs", source_dir),"/", pheno, "*"),
         rm_train_cent_plots = paste0(gsub("model_objs", "centile_plots", source_dir),"/", pheno, "*"),
         rm_train_mod_sums = paste0(gsub("model_objs", "model_sums", source_dir),"/", pheno, "*"),
         rm_train_wp = paste0(gsub("model_objs", "worm_plots", source_dir),"/", pheno, "*"),
         test_file = case_when(
           str_detect(file, "A_train") ~ str_replace(file, "A_train", "B_test"),
           str_detect(file, "B_train") ~ str_replace(file, "B_train", "A_test"),
           TRUE ~ NA_character_)) %>%
  mutate(rm_test_file = paste0(gsub("model_objs", "*", dirname(test_file)),"/", pheno, "*"))#rename BestMod
  #rm other downstream outputs of that pheno

all_to_rm <- c(to_delete, #rm non-converged files
               unique(dnc$rm_train_cent_csvs), #downstream training outputs
               unique(dnc$rm_train_cent_cent_plots), 
               unique(dnc$rm_train_mod_sums), 
               unique(dnc$rm_train_wp), 
               unique(dnc$rm_test_file)) #downstream testing outputs

readr::write_lines(all_to_rm, "./convergence_rm.txt")

all_to_rename <- unique(dnc$BestMod_rename)
readr::write_lines(all_to_rename, "./convergence_rename.txt")
```

check by pheno
```{r}
convergence_sum <- merged_df %>% 
  mutate(pheno = sub("_.*", "", file)) %>% 
  group_by(cv_sample, pheno) %>% 
  summarise(n_failed = sum(converged==FALSE)) %>%
  mutate(rerun = ifelse(n_failed==0, FALSE, TRUE))

table(convergence_sum$rerun)
```

For all phenos that have non-converged models, need to:
1) delete non-converged models
2) rename "_BestMod.rds" to "_mod.rds"
3) remove pngs of fan plots, worm plots, test outputs
4) rerun fit_cv_mods.R - write new config file with just these phenos?

