---
title: "sensitivity_df_prep"
output: html_document
date: "2025-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
```

Prep split-half dataframes for sensitivity analyses with stricter scan QC

```{r, warning=FALSE}}
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, dplyr)
```

load data cleaned data
```{r}
df_euler <- fread("./data/euler_tmp.csv", stringsAsFactors=T)
skimr::skim(df_euler$SurfaceHoles)
```

look just at data with euler

```{r}
df_euler <- df_euler %>%
  filter(!is.na(SurfaceHoles))
range(df_euler$SurfaceHoles)
range(df_euler$age_days)

df_euler %>%
  ggplot() +
  geom_boxplot(aes(x=study, y=SurfaceHoles))
```

playing around with re-scaling euler w/in study
```{r}
df_euler2 <- df_euler %>%
  group_by(study) %>%
  mutate(SurfaceHoles_scaled = (SurfaceHoles - min(SurfaceHoles, na.rm = TRUE)) /
                               (max(SurfaceHoles, na.rm = TRUE) - min(SurfaceHoles, na.rm = TRUE))) %>%
  ungroup()

df_euler2 %>%
  ggplot() +
  geom_boxplot(aes(x=study, y=SurfaceHoles_scaled))

df_euler2 %>%
  ggplot() +
  geom_point(aes(x=logAge_days, y=SurfaceHoles_scaled))
df_euler2 %>%
  ggplot() +
  geom_point(aes(x=logAge_days, y=SurfaceHoles))
```

using weight-deriving formula from Kat's analyses
```{r}
df_euler2$weight <- (1 - df_euler2$SurfaceHoles_scaled) * (nrow(df_euler2) / sum(1 - df_euler2$SurfaceHoles_scaled))
sum(df_euler2$weight)
nrow(df_euler2)
stopifnot(all.equal(sum(df_euler2$weight), nrow(df_euler2)))

df_euler2 %>%
  ggplot() +
  geom_point(aes(x=weight, y=SurfaceHoles_scaled))
```

use the original splits and just add back in Euler weights for consistency with main analyses
```{r}
#remove any cols that could be different/imact merge
rm_cols <- c("SurfaceHoles", "study_euler_mad", "study_euler_median", "euler_threshold", "has_qc")

og_sample_A <- fread("./data/cv_sample_A.csv", stringsAsFactors=T) %>% 
  select(!any_of(rm_cols))
og_sample_B <- fread("./data/cv_sample_B.csv", stringsAsFactors=T) %>% 
  select(!any_of(rm_cols))

og_sample_A_weight <- right_join(og_sample_A, df_euler2)
og_sample_B_weight <- right_join(og_sample_B, df_euler2)

og_sample_A_weight$sample <- "A"
og_sample_B_weight$sample <- "B"

og_splits <- rbind(og_sample_A_weight, og_sample_B_weight)
stopifnot(sum(is.na(og_splits$SurfaceHoles))==0)
```

```{r}
ggplot(og_splits)+
  geom_violin(aes(x=sample, y=age_days, fill=as.factor(sexMale))) +
  theme_linedraw() +
  labs(fill = "Male")

ggplot(og_splits)+
  geom_histogram(aes(x=weight, fill=as.factor(sample)), position="identity", alpha=0.5)

table(og_splits$sample, og_splits$sex)

ggplot(og_splits)+
  geom_bar(aes(x=study_site, fill=sample), position = "fill") +
  theme_linedraw()

ggplot(og_splits)+
  geom_bar(aes(x=sample, fill=study_site), position = "fill") +
  theme_linedraw() +
  theme(legend.position="none")
```


```{r}
og_splits %>% 
  filter(study=="SLIP") %>%
  ggplot() +
  geom_violin(aes(x=sample, y=age_days, fill=as.factor(sexMale)))
```

save
```{r}
fwrite(og_sample_A_weight, "./data/cv_sample_A_euler.csv")
fwrite(og_sample_B_weight, "./data/cv_sample_B_euler.csv")
```