---
title: "Untitled"
output: html_document
date: "2026-02-11"
---

```{r setup, include=FALSE}
setwd("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts")
library(data.table)
library(dplyr)
library(gamlss)
library(gamlssTools)
```

looking into sample B test rh.CT.insula

```{r}
df <- fread("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/data/cv_sample_B_dfs/rh.CT.insula_totalTRUE_logPhenoFALSE_logAgeTRUE.csv", stringsAsFactors = T)
model <- readRDS("/mnt/isilon/bgdlab_processing/Margaret/sex_mod_braincharts/cv_sample_B_test/cortical_thickness_totalTRUE_logAgeTRUE_pbmods/model_objs/rh.CT.insula_fsall_age_totalall_test_full_mod.rds")

model$call$data <- "df"
model$call$family <- model$family[[1]]
```

try plotting

```{r}
pheno <- model$mu.terms[[2]] %>% as.character()

pred_list <- list_predictors(model)

#check if age is log-scaled
if ("logAge_days" %in% pred_list){
  age_var <- "logAge_days"
  print("simulate data for plotting")
  sim_df <- sim_data(df, age_var, factor_var="sexMale", special_term = "sexMale_x_logAge = sexMale * logAge_days")
  vars_of_interest <- c("sexMale_x_logAge", age_var, "sexMale")
} else {
  print("simulate data for plotting")
  age_var <- "age_days"
  sim_df <- sim_data(df, age_var, factor_var="sexMale", special_term = "sexMale_x_age = sexMale * age_days")
  vars_of_interest <- c("sexMale_x_age", age_var, "sexMale")
}

#define nuisance covars to residualize from points
resid_terms <- setdiff(pred_list, vars_of_interest)

birth <- log(280, base=10)
print("creating centile fan plot")
  fan_plot <- make_centile_fan(gamlssModel=model, 
                               df=df, 
                               x_var=age_var, 
                               color_var="sexMale",
                               get_peaks=TRUE, 
                               desiredCentiles=c(0.05, 0.25, 0.5, 0.75, 0.95),
                               sim_data_list = sim_df,
                               remove_point_effect = resid_terms,
                               x_axis="log_lifespan_fetal")  +
    theme_linedraw() +
    labs(title=paste(pheno, "validation model"),
         x ="log Age (days)") +
  scale_color_discrete(name = "Sex", labels = c("Female", "Male")) +
    guides(fill=FALSE) +
    geom_vline(xintercept=birth)
```

```{r}
sim_df

make_centile_fan(gamlssModel=model, 
                               df=df, 
                               x_var=age_var, 
                               color_var="sexMale",
                               get_peaks=TRUE, 
                               desiredCentiles=c(0.05, 0.25, 0.5, 0.75, 0.95),
                               sim_data_list = sim_df,
                               x_axis="log_lifespan_fetal")
```
